<?php

return [
    'catalog' => [
        'default_view_limit' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'playback',
            'type' => 'integer',
            'storage' => 'center_settings.settings.default_view_limit',
            'fallback' => 'centers.default_view_limit',
            'default' => 2,
            'system_limit' => 'max_view_limit',
            'rules' => ['integer', 'min:0'],
        ],
        'allow_extra_view_requests' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'playback',
            'type' => 'boolean',
            'storage' => 'center_settings.settings.allow_extra_view_requests',
            'fallback' => 'centers.allow_extra_view_requests',
            'default' => true,
            'system_override' => 'force_disable_extra_view_requests',
            'rules' => ['boolean'],
        ],
        'pdf_download_permission' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'downloads',
            'type' => 'boolean',
            'storage' => 'center_settings.settings.pdf_download_permission',
            'fallback' => 'centers.pdf_download_permission',
            'default' => false,
            'system_override' => 'force_disable_pdf_download',
            'feature_flag' => 'pdf_downloads',
            'rules' => ['boolean'],
        ],
        'device_limit' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'devices',
            'type' => 'integer',
            'storage' => 'center_settings.settings.device_limit',
            'fallback' => 'centers.device_limit',
            'default' => 1,
            'system_limit' => 'max_device_limit',
            'rules' => ['integer', 'min:1'],
        ],
        'branding' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'branding',
            'type' => 'object',
            'storage' => 'center_settings.settings.branding',
            'fallback' => 'centers.logo_url,centers.primary_color',
            'default' => [],
            'rules' => ['array'],
            'properties' => [
                'logo_url' => [
                    'type' => 'string',
                    'default' => null,
                    'rules' => ['nullable', 'string'],
                ],
                'primary_color' => [
                    'type' => 'string',
                    'default' => null,
                    'rules' => ['nullable', 'string'],
                ],
            ],
        ],
        'education_profile' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'student_profile',
            'type' => 'object',
            'storage' => 'center_settings.settings.education_profile',
            'default' => [
                'enable_grade' => true,
                'enable_school' => true,
                'enable_college' => true,
                'enable_parent_phone' => true,
                'require_grade' => false,
                'require_school' => false,
                'require_college' => false,
                'require_parent_phone' => false,
            ],
            'rules' => ['array'],
            'properties' => [
                'enable_grade' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'enable_school' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'enable_college' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'enable_parent_phone' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'require_grade' => [
                    'type' => 'boolean',
                    'default' => false,
                    'rules' => ['boolean'],
                ],
                'require_school' => [
                    'type' => 'boolean',
                    'default' => false,
                    'rules' => ['boolean'],
                ],
                'require_college' => [
                    'type' => 'boolean',
                    'default' => false,
                    'rules' => ['boolean'],
                ],
                'require_parent_phone' => [
                    'type' => 'boolean',
                    'default' => false,
                    'rules' => ['boolean'],
                ],
            ],
        ],
        'allow_guest_browsing' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'guest',
            'type' => 'boolean',
            'storage' => 'center_settings.settings.allow_guest_browsing',
            'fallback' => 'centers.allow_guest_browsing',
            'default' => false,
            'system_override' => 'force_disable_guest_browsing',
            'feature_flag' => 'guest_browsing',
            'rules' => ['boolean'],
        ],
        'requires_video_approval' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'video_access',
            'type' => 'boolean',
            'storage' => 'center_settings.settings.requires_video_approval',
            'default' => false,
            'rules' => ['boolean'],
        ],
        'video_code_expiry_days' => [
            'scope' => 'center',
            'managed_by' => 'center',
            'group' => 'video_access',
            'type' => 'integer',
            'storage' => 'center_settings.settings.video_code_expiry_days',
            'default' => null,
            'feature_flag' => 'codes_access',
            'rules' => ['nullable', 'integer', 'min:1'],
        ],
        'features' => [
            'scope' => 'center',
            'managed_by' => 'system',
            'group' => 'feature_flags',
            'type' => 'object',
            'storage' => 'center_settings.settings.features',
            'default' => [
                'ai_content' => true,
                'codes_access' => true,
                'whatsapp_bulk' => true,
                'guest_browsing' => true,
                'pdf_downloads' => true,
            ],
            'rules' => ['array'],
            'properties' => [
                'ai_content' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'codes_access' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'whatsapp_bulk' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'guest_browsing' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
                'pdf_downloads' => [
                    'type' => 'boolean',
                    'default' => true,
                    'rules' => ['boolean'],
                ],
            ],
        ],
        'site_name' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'general',
            'type' => 'object',
            'storage' => 'system_settings.key=site_name',
            'default' => [
                'en' => 'Najaah LMS',
                'ar' => 'نظام إدارة التعلم Najaah',
            ],
        ],
        'timezone' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'general',
            'type' => 'string',
            'storage' => 'system_settings.key=timezone',
            'default' => 'UTC',
        ],
        'support_email' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'general',
            'type' => 'string',
            'storage' => 'system_settings.key=support_email',
            'default' => 'support@example.com',
        ],
        'require_device_approval' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'security',
            'type' => 'boolean',
            'storage' => 'system_settings.key=require_device_approval',
            'default' => false,
        ],
        'attendance_required' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'security',
            'type' => 'boolean',
            'storage' => 'system_settings.key=attendance_required',
            'default' => false,
        ],
        'whatsapp_bulk_settings' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'infrastructure',
            'type' => 'object',
            'storage' => 'system_settings.key=whatsapp_bulk_settings',
            'default' => [
                'delay_seconds' => 3,
                'batch_size' => 50,
                'batch_pause_seconds' => 60,
                'max_retries' => 2,
                'max_failures_before_pause' => 10,
            ],
        ],
        'max_view_limit' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'limits',
            'type' => 'integer',
            'storage' => 'system_settings.key=max_view_limit',
            'default' => 10,
        ],
        'max_device_limit' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'limits',
            'type' => 'integer',
            'storage' => 'system_settings.key=max_device_limit',
            'default' => 3,
        ],
        'force_disable_extra_view_requests' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'overrides',
            'type' => 'boolean',
            'storage' => 'system_settings.key=force_disable_extra_view_requests',
            'default' => false,
        ],
        'force_disable_pdf_download' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'overrides',
            'type' => 'boolean',
            'storage' => 'system_settings.key=force_disable_pdf_download',
            'default' => false,
        ],
        'force_disable_guest_browsing' => [
            'scope' => 'system',
            'managed_by' => 'system',
            'group' => 'overrides',
            'type' => 'boolean',
            'storage' => 'system_settings.key=force_disable_guest_browsing',
            'default' => false,
        ],
    ],
];
