<?php

declare(strict_types=1);

namespace App\Support;

final class ErrorCodes
{
    public const NOT_FOUND = 'NOT_FOUND';

    public const CENTER_MISMATCH = 'CENTER_MISMATCH';

    public const UNAUTHORIZED = 'UNAUTHORIZED';

    public const FORBIDDEN = 'FORBIDDEN';

    public const UPLOAD_NOT_READY = 'UPLOAD_NOT_READY';

    public const UPLOAD_FAILED = 'UPLOAD_FAILED';

    public const VIDEO_NOT_READY = 'VIDEO_NOT_READY';

    public const PDF_NOT_READY = 'PDF_NOT_READY';

    public const ATTACHMENT_NOT_ALLOWED = 'ATTACHMENT_NOT_ALLOWED';

    public const COURSE_PUBLISH_BLOCKED = 'COURSE_PUBLISH_BLOCKED';

    public const CONCURRENT_DEVICE = 'CONCURRENT_DEVICE';

    public const ENROLLMENT_REQUIRED = 'ENROLLMENT_REQUIRED';

    public const SESSION_ENDED = 'SESSION_ENDED';

    public const SESSION_EXPIRED = 'SESSION_EXPIRED';

    public const SESSION_NOT_FOUND = 'SESSION_NOT_FOUND';

    public const NO_ACTIVE_DEVICE = 'NO_ACTIVE_DEVICE';

    public const VIEW_LIMIT_EXCEEDED = 'VIEW_LIMIT_EXCEEDED';

    public const DEVICE_MISMATCH = 'DEVICE_MISMATCH';

    public const DEVICE_REVOKED = 'DEVICE_REVOKED';

    public const INVALID_STATE = 'INVALID_STATE';

    public const INVALID_VIEWS = 'INVALID_VIEWS';

    public const VIDEO_NOT_IN_COURSE = 'VIDEO_NOT_IN_COURSE';

    public const PENDING_REQUEST_EXISTS = 'PENDING_REQUEST_EXISTS';

    public const VIEWS_AVAILABLE = 'VIEWS_AVAILABLE';

    public const VIDEO_ACCESS_DENIED = 'VIDEO_ACCESS_DENIED';

    public const VIDEO_ACCESS_REQUEST_EXISTS = 'VIDEO_ACCESS_REQUEST_EXISTS';

    public const VIDEO_ACCESS_ALREADY_GRANTED = 'VIDEO_ACCESS_ALREADY_GRANTED';

    public const VIDEO_CODE_INVALID = 'VIDEO_CODE_INVALID';

    public const VIDEO_CODE_ALREADY_REDEEMED = 'VIDEO_CODE_ALREADY_REDEEMED';

    public const VIDEO_CODE_ALREADY_REDEEMED_BY_YOU = 'VIDEO_CODE_ALREADY_REDEEMED_BY_YOU';

    public const VIDEO_CODE_EXPIRED = 'VIDEO_CODE_EXPIRED';

    public const VIDEO_CODE_USED = 'VIDEO_CODE_USED';

    public const VIDEO_CODE_REVOKED = 'VIDEO_CODE_REVOKED';

    public const VIDEO_CODE_WRONG_USER = 'VIDEO_CODE_WRONG_USER';

    public const VIDEO_CODE_ACTIVE_EXISTS = 'VIDEO_CODE_ACTIVE_EXISTS';

    public const VIDEO_CODE_BATCH_ACTIVE_EXISTS = 'VIDEO_CODE_BATCH_ACTIVE_EXISTS';

    public const VIDEO_CODE_BATCH_CLOSED = 'VIDEO_CODE_BATCH_CLOSED';

    public const VIDEO_CODE_BATCH_LIMIT_REACHED = 'VIDEO_CODE_BATCH_LIMIT_REACHED';

    public const VIDEO_CODE_BATCH_NOT_FOUND = 'VIDEO_CODE_BATCH_NOT_FOUND';

    public const VIDEO_CODE_VIDEO_MISMATCH = 'VIDEO_CODE_VIDEO_MISMATCH';

    public const STUDENT_NO_PHONE = 'STUDENT_NO_PHONE';

    public const WHATSAPP_SEND_FAILED = 'WHATSAPP_SEND_FAILED';

    public const ALREADY_ENROLLED = 'ALREADY_ENROLLED';

    public const NOT_ADMIN = 'NOT_ADMIN';

    public const NOT_STUDENT = 'NOT_STUDENT';

    public const OTP_INVALID = 'OTP_INVALID';

    public const USER_NOT_FOUND_FOR_OTP = 'USER_NOT_FOUND_FOR_OTP';

    public const STUDENT_INACTIVE = 'STUDENT_INACTIVE';

    public const STUDENT_BANNED = 'STUDENT_BANNED';

    public const STUDENT_DELETE_DISABLED = 'STUDENT_DELETE_DISABLED';

    public const AI_PROVIDER_NOT_AVAILABLE = 'AI_PROVIDER_NOT_AVAILABLE';

    public const AI_PROVIDER_NOT_CONFIGURED = 'AI_PROVIDER_NOT_CONFIGURED';

    public const AI_MODEL_NOT_ALLOWED = 'AI_MODEL_NOT_ALLOWED';

    public const AI_LIMIT_DAILY_JOBS_EXCEEDED = 'AI_LIMIT_DAILY_JOBS_EXCEEDED';

    public const AI_LIMIT_MONTHLY_JOBS_EXCEEDED = 'AI_LIMIT_MONTHLY_JOBS_EXCEEDED';

    public const AI_LIMIT_DAILY_TOKENS_EXCEEDED = 'AI_LIMIT_DAILY_TOKENS_EXCEEDED';

    public const AI_LIMIT_MONTHLY_TOKENS_EXCEEDED = 'AI_LIMIT_MONTHLY_TOKENS_EXCEEDED';

    public const AI_LIMIT_CONCURRENT_JOBS_EXCEEDED = 'AI_LIMIT_CONCURRENT_JOBS_EXCEEDED';

    public const AI_LIMIT_INPUT_TOO_LARGE = 'AI_LIMIT_INPUT_TOO_LARGE';

    public const AI_LIMIT_OUTPUT_TOO_LARGE = 'AI_LIMIT_OUTPUT_TOO_LARGE';

    public const TRANSCRIPT_NOT_FOUND = 'TRANSCRIPT_NOT_FOUND';

    public const PDF_TEXT_EXTRACTION_FAILED = 'PDF_TEXT_EXTRACTION_FAILED';

    public const SYSTEM_LIMIT_EXCEEDED = 'SYSTEM_LIMIT_EXCEEDED';

    private function __construct() {}
}
